services:
  - type: web
    name: ygc-chits-app
    runtime: docker
    region: singapore
    plan: standard
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

