name: CI Validation

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build and Test
        run: mvn clean verify
      - name: SonarCloud Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=vinaykumar666 \
            -Dsonar.projectKey=vinaykumar666_chits-app \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}